"""
explain.py — Knowledge base and logic for the `mac-care explain` command.

Provides detailed rationale, risk definitions, and category-specific
context for scan findings.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json
from typing import TypedDict

from .model import Finding, format_bytes
from .ids import finding_id as get_finding_id


class CategoryExplanation(TypedDict):
    title: str
    description: str
    risk_rationale: str
    safety_tip: str


KNOWLEDGE_BASE: dict[str, CategoryExplanation] = {
    "user_logs": {
        "title": "User Logs",
        "description": "Application and system logs generated by your user account.",
        "risk_rationale": "Logs are useful for troubleshooting recent crashes. Once a few days have passed, older logs are usually safe to delete.",
        "safety_tip": "Check if you are currently troubleshooting an issue before clearing logs."
    },
    "user_caches": {
        "title": "User Caches",
        "description": "Temporary data stored by applications to speed up performance.",
        "risk_rationale": "Caches are meant to be rebuildable. However, clearing active caches can cause temporary slowness while apps re-generate them.",
        "safety_tip": "mac-care applies age filters to ensure only 'stale' caches are targeted."
    },
    "trash": {
        "title": "Trash",
        "description": "Files you have manually moved to the Trash but not yet permanently deleted.",
        "risk_rationale": "Items in the trash are already marked for deletion. mac-care helps automate the final purge of old trash.",
        "safety_tip": "Do not use the Trash as a long-term storage folder."
    },
    "tmp": {
        "title": "Temporary Files",
        "description": "System and application temporary files in /tmp.",
        "risk_rationale": "These files are usually transient. macOS clears most of these on reboot, but they can accumulate between reboots.",
        "safety_tip": "mac-care only targets old temporary files to avoid disrupting active processes."
    },
    "xcode_derived_data": {
        "title": "Xcode Derived Data",
        "description": "Build artifacts, indexes, and intermediate files generated by Xcode.",
        "risk_rationale": "DerivedData can grow to tens of gigabytes. It is entirely rebuildable by Xcode on the next build.",
        "safety_tip": "Deleting this will cause the next build for each project to be a 'clean build' (slower)."
    },
    "xcode_archives": {
        "title": "Xcode Archives",
        "description": "Bundled versions of your apps ready for distribution or App Store upload.",
        "risk_rationale": "Archives contain dSYM files necessary for de-symbolicating crash logs from the field.",
        "safety_tip": "Review your archives and delete only those for versions you no longer support."
    },
    "xcode_unavailable_simulator": {
        "title": "Unavailable Simulators",
        "description": "Disk data left behind by iOS/watchOS/tvOS simulators that are no longer supported by your current Xcode version.",
        "risk_rationale": "These simulators cannot be booted or used, but their data (apps, settings) remains on disk.",
        "safety_tip": "Use `xcrun simctl delete unavailable` to clear these safely."
    },
    "xcode_device_support": {
        "title": "Xcode Device Support",
        "description": "Symbol files extracted from physical devices to enable on-device debugging.",
        "risk_rationale": "Xcode keeps symbols for every OS version of every device you've plugged in. These accumulate over years.",
        "safety_tip": "Safe to delete if you are no longer debugging on those specific OS versions."
    },
    "brew_cache": {
        "title": "Homebrew Cache",
        "description": "Downloaded source tarballs and bottles for Homebrew formulae.",
        "risk_rationale": "Homebrew keeps these to allow for faster re-installs, but they are easily re-downloaded.",
        "safety_tip": "mac-care uses `brew cleanup`'s own logic to determine what is safe."
    },
    "docker_images": {
        "title": "Docker Images",
        "description": "Stored Docker images, including intermediate layers and dangling images.",
        "risk_rationale": "Dangling images (those without a tag) are often useless waste. Large tagged images can also accumulate.",
        "safety_tip": "Use `docker image prune` to clear unused images."
    },
    "docker_volumes": {
        "title": "Docker Volumes",
        "description": "Persistent data volumes used by Docker containers.",
        "risk_rationale": "Volumes often contain persistent data (like databases). If the container is gone, the volume might be an orphan.",
        "safety_tip": "Be extremely careful as volumes contain the actual data you might want to keep."
    },
    "docker_build_cache": {
        "title": "Docker Build Cache",
        "description": "Layers cached by the Docker builder (BuildKit) to speed up image creation.",
        "risk_rationale": "Build caches can grow indefinitely if not pruned.",
        "safety_tip": "Safe to clear; the next build will simply be slower as it re-downloads/re-builds layers."
    },
    "ios_backups": {
        "title": "iOS Backups",
        "description": "Local backups of iPhones or iPads made via Finder or iTunes.",
        "risk_rationale": "These are high-fidelity backups. If you have iCloud backups, local ones might be redundant.",
        "safety_tip": "Always keep at least one recent local backup if you don't use iCloud."
    },
    "messages_attachments": {
        "title": "iMessage Attachments",
        "description": "Photos, videos, and files sent or received via the Messages app.",
        "risk_rationale": "These are personal data. Deleting them from the filesystem will remove them from your message history.",
        "safety_tip": "Review these manually; mac-care will never auto-delete personal attachments."
    },
    "login_items": {
        "title": "Login Items",
        "description": "Applications configured to start automatically when you log in.",
        "risk_rationale": "Too many login items can significantly slow down your boot time and consume background memory.",
        "safety_tip": "Check System Settings → General → Login Items to manage these."
    },
    "stale_runtimes": {
        "title": "Stale Language Runtimes",
        "description": "Old versions of Node.js, Python, or Ruby installed via version managers like nvm, pyenv, or rbenv.",
        "risk_rationale": "Version managers often keep every version you've ever used. Older versions are rarely needed.",
        "safety_tip": "Ensure you don't have legacy projects that strictly require an old version before deleting."
    },
    "orphan_dotdir": {
        "title": "Orphaned Dot-Directories",
        "description": "Hidden directories in your home folder belonging to CLI tools that are no longer installed.",
        "risk_rationale": "When you uninstall a tool, it often leaves its configuration and cache folder behind.",
        "safety_tip": "Usually safe to delete if the tool is truly no longer on your system."
    },
    "cursor_cache": {
        "title": "Cursor Cache",
        "description": "Cache files for the Cursor AI code editor.",
        "risk_rationale": "Large caches can slow down the editor's indexing or just waste disk space.",
        "safety_tip": "Safe to delete; Cursor will re-index or re-cache as needed."
    },
    "claude_cache": {
        "title": "Claude Cache",
        "description": "Cache files for the Claude desktop application.",
        "risk_rationale": "Temporary files and webview caches that can grow over time.",
        "safety_tip": "Safe to delete; the app will regenerate them on next launch."
    },
    "playwright_cache": {
        "title": "Playwright Browsers",
        "description": "Hermetic browser binaries (Chromium, Firefox, WebKit) downloaded by Playwright.",
        "risk_rationale": "Playwright keeps many large browser versions. These can take up several gigabytes.",
        "safety_tip": "If you are not actively using Playwright for testing, these are safe to remove."
    },
    "xcode_simulator_artifacts": {
        "title": "Simulator Artifacts",
        "description": "Simulator caches, profiles, and runtimes used by CoreSimulator.",
        "risk_rationale": "These are support files for the iOS simulator environment.",
        "safety_tip": "Review before removing if you are an active iOS developer."
    },
    "broken_symlinks": {
        "title": "Broken Symbolic Links",
        "description": "Links that point to a file or directory that no longer exists.",
        "risk_rationale": "Broken links are harmless but cluttered. They often indicate that a tool or file was moved or deleted incompletely.",
        "safety_tip": "Safe to delete as they don't point to anything."
    }
}

RISK_DEFINITIONS: dict[str, str] = {
    "auto_safe": "High confidence. This item is rebuildable, transient, or already marked for deletion (like Trash). Safe to automate.",
    "review": "Action required. This item may contain personal data, unique archives, or important caches. Review before acting.",
    "protected": "Off-limits. This path is either system-critical, specifically excluded in your config, or contains active git work."
}


@dataclass(frozen=True)
class Explanation:
    category: str
    title: str
    description: str
    risk: str
    risk_definition: str
    risk_rationale: str
    safety_tip: str
    path: str | None = None
    size: str | None = None
    reason: str | None = None

    def render(self) -> str:
        lines = [
            f"Explanation for: {self.title} ({self.category})",
            "=" * (17 + len(self.title) + len(self.category)),
            f"\nDescription: {self.description}",
            f"\nRisk Level: {self.risk.upper()}",
            f"Definition: {self.risk_definition}",
            f"Rationale:  {self.risk_rationale}",
            f"\nSafety Tip:  {self.safety_tip}",
        ]
        if self.path:
            lines.insert(2, f"Path:        {self.path}")
        if self.size:
            lines.insert(3, f"Size:        {self.size}")
        if self.reason:
            lines.insert(4, f"Finding:     {self.reason}")
        
        return "\n".join(lines)


def explain_finding(finding_id: str, report_path: Path) -> str:
    """Find a finding by ID in a report and return a detailed explanation."""
    if not report_path.exists():
        return f"Error: Report not found at {report_path}"

    try:
        data = json.loads(report_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        return f"Error reading report: {e}"

    findings = data.get("findings", [])
    target = None
    for f in findings:
        # We need to reconstruct the ID or hope it's in the JSON (it should be if we use the right model)
        # Actually, our report JSON currently doesn't include the ID. 
        # We might need to match by reconstruction.
        from .model import Finding
        from .ids import finding_id as get_id
        
        # Convert dict to Finding object to get ID
        try:
            f_obj = Finding(
                category=f["category"],
                path=f["path"],
                size_bytes=f["size_bytes"],
                risk=f["risk"],
                reason=f["reason"],
                source=f.get("source", "native")
            )
            if get_id(f_obj) == finding_id:
                target = f
                break
        except KeyError:
            continue

    if not target:
        return f"Error: Finding with ID '{finding_id}' not found in {report_path.name}"

    return _explain_category(
        target["category"],
        risk=target["risk"],
        path=target["path"],
        size_bytes=target["size_bytes"],
        reason=target["reason"]
    ).render()


def explain_category(category: str) -> str:
    """Explain a category in general."""
    return _explain_category(category).render()


def _explain_category(
    category: str, 
    risk: str | None = None, 
    path: str | None = None, 
    size_bytes: int | None = None,
    reason: str | None = None
) -> Explanation:
    meta = KNOWLEDGE_BASE.get(category, {
        "title": category.replace("_", " ").title(),
        "description": "No detailed description available for this category.",
        "risk_rationale": "Rationale depends on the specific item and your usage.",
        "safety_tip": "Review this item carefully before taking action."
    })
    
    # Use provided risk or default to something sensible
    final_risk = risk or "review"
    risk_def = RISK_DEFINITIONS.get(final_risk, "No definition available for this risk level.")

    return Explanation(
        category=category,
        title=meta["title"],
        description=meta["description"],
        risk=final_risk,
        risk_definition=risk_def,
        risk_rationale=meta["risk_rationale"],
        safety_tip=meta["safety_tip"],
        path=path,
        size=format_bytes(size_bytes) if size_bytes is not None else None,
        reason=reason
    )
